import { Montserrat } from 'next/font/google';
import "./globals.css";
import Sidebar from './components/Sidebar';
import Sidebaroo from './components/Sidebar2';
import ReactQueryProvider from './services/react-query/queryClient';

const montserrat = Montserrat({
  subsets: ['latin'], // Include necessary subsets
  weight: ['400', '700'], // Specify required font weights
  display: 'swap', // Ensure font loads gracefully
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReactQueryProvider>
          
        <Sidebar/>
        {children}
        <Sidebaroo/>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
